### ISSUE TITLE
Ice Traps are Not Shared to Other Players (in Multiworld)

### ISSUE THREAD

**Issue by rehashedsalt** [hylian-modding/OcarinaOfTimeOnline#28]
Probably one of my favorite parts of rando is hitting friends with Ice Traps, and right now the OOTOnline implementation does not actually freeze a player when someone from another world receives an ice trap for them. Makes getting one pretty unsatisfying.

It's debatable whether Ice Traps should propagate in other scenarios, but it should at the very least be supported for MW.

**Comment by denoflionsx** [comment]
I'm aware. One of the first things I said when I rolled out MW support was
that ice traps didn't work.

It'll get fixed... one day. MW stuff is incredibly dead last on my
priorities. No one on the dev team plays multiworld and none of our
internal testers do either.

**Comment by denoflionsx** [comment]
As Loco pointed out to me in Discord, I apparently already fixed this but it hasn't made its way to the live build yet.

ee2892f7a9acb4a5c432a1af135dc32d866fb299

**Comment by rehashedsalt** [comment]
Sweet, I'll keep an eye out for the next release then!

Sorry if MW is a sore topic for you; I'm not part of the Discord so the only development history I can see here is in issues and commit logs.

**Comment by denoflionsx** [comment]
Apologies if I came across that way. I swear I'm not actually a raging
asshole about MW.

I just do most of the development by myself and have a ludicrous amount of
work on the docket at any given time.

**Comment by rehashedsalt** [comment]
All good, I understand completely. Development is only really a hobby for me, but if you ever have any "good first issue" type jobs laying around, ping me; I'd be more than happy to contribute.
